version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "docker"
    directory: "/minimal"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "nuget"
    directory: "/minimal"
    schedule:
      interval: "weekly"
  
